name: study_time
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^2.15.0
  cloud_firestore: ^4.9.2
  get_it: ^7.6.0
  firebase_auth: ^4.7.2
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  firebase_crashlytics: ^3.3.4
  dio: ^5.1.2
  google_fonts: ^4.0.4
  collection: ^1.17.1
  flutter_modular: 6.3.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon_launcher.jpg"
  min_sdk_android: 21 
  

flutter:
  uses-material-design: true
